version: '3'
services:
    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=proj
            - MYSQL_USER=devel
            - MYSQL_PASSWORD=bazinga
        ports:
            - 6033:3306
        volumes:
            - ./mysql:/share
    web:
        # image: php:7.3-apache to use docker hub's image, 
        # build: ... to build a custom image from dockerfile
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: php7.3
        ports:
            - 8080:80
        depends_on:
            - db
        volumes:
            - ./php:/var/www/html

